# version: '3'

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:12
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./data:/data
