version: '3.9'

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:12
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./data:/data

  forgejo-runner:
    image: code.forgejo.org/forgejo/runner:latest
    container_name: forgejo-runner
    restart: unless-stopped
    privileged: true
    volumes:
      - ./runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
 